### PR TITLE
feat(corporate-structure): add corporate structure attribute

### PR DESCRIPTION
**Pull request by sk91**

### CODE REVIEW

**Comment by felipewer** [comment]
@sk91 , have thought about adding Unit Tests for attributes. To test out that some expected attribute value validate against the schema. This specif one is very complex and sure could use some tests.

**Comment by sk91** [comment]
This is a goos idea, till now I’ve been testing it by dereferencing the attribute and running it in react-json-schema form play ground

But some actual test might make the provess easier

**Comment by andregoncalves** [comment]
> @sk91 , have you thought about adding Unit Tests for attributes. To test out that some expected attribute value validates against the schema. This specif one is very complex and sure could use some tests.

+1 for that. I'm having a hard time wrapping my head around the definition. At first sight seems too complex and rigid to represent the subject, but for now I don't see any other alternatives.  This is great work @sk91 !

The only thing I'm hesitant is the decision to mix equity holders (like shareholders and members) with executive positions in the positions definition.
In my view, equity holding is a formal concept separated from executive roles (like a Director, CEO)
So, I would prefer to have a members array and separated "owners" array. 
Having it separated would also help to enforce/validate 100 as the sum of all the equity holders in the array.

**Comment by sk91** [comment]
> The only thing I'm hesitant is the decision to mix equity holders (like shareholders and members) with executive positions in the positions definition.

Hmm, this is a different model than we had in mind, and it does not serve us in any other use-case besides ease of validation.

I would argue against. Current structure:

```
{
  "companyType": "Company Limited by Shares (LTD)",
  "members": [
    {
      "entity": {
        "type": "individual",
        "firstName": "Maxim",
        "lastName": "Kovalov",
        "email": "test@gmail.com"
      },
      "positions": [
        {
          "position": "director"
        },
        {
          "position": "shareholder",
          "equity": 19
        }
      ]
    },
    {
      "entity": {
        "type": "corporate",
        "companyType": "Company Limited by Shares (LTD)",
        "companyName": "Test Company name",
        "email": "test@company.org"
      },
      "positions": [
        {
          "position": "observer"
        }
      ]
    }
  ]
}
```

**Comment by andregoncalves** [comment]
Agree, it works and probably makes dev a little easier. 

Anyway, my comment was more of an attempt to better represent the real-world concept, and to make the schema more understandable and easy to adapt to changes in the future.
The shareholding/ownership requires an equity attribute of the relationship, the other positions don't require any. It's probably a hint that shareholding is not the same as the others.

Any opinion regarding this @felipewer ?

**Comment by sk91** [comment]
> Agree, it works and probably makes dev a little easier.
> 
> Anyway, my comment was more of an attempt to better represent the real-world concept, and to make the schema more understandable and easy to adapt to changes in the future.
> The shareholding/ownership requires an equity attribute of the relationship, the other positions don't require any. It's probably a hint that shareholding is not the same as the others.
> 
> Any opinion regarding this @felipewer ?

keep in mind that some company types don't have owners, or owners don't have equity. It is complex.

But we can open this question for discussion with @Horizon88 in mattermost

**Comment by sk91** [comment]
@andregoncalves @felipewer added tests please review again

**Pull request merged**
